services:
  nginx:
    image: nginx:latest
    ports:
      - 127.0.0.1:8082:80
    volumes:
      - ../:/web/mclogs
      - ./mclogs.conf:/etc/nginx/conf.d/default.conf
    links:
      - php-fpm
  php-fpm:
    build:
      dockerfile_inline: |
        FROM php:8.1-fpm

        RUN apt-get update && apt-get install -y \
          git \
          unzip \
          zip \
          && rm -rf /var/lib/apt/lists/*

        # Install PHP extensions
        COPY --from=mlocati/php-extension-installer /usr/bin/install-php-extensions /usr/local/bin/
        RUN install-php-extensions mongodb-1.20.0

        # Install Composer
        COPY --from=composer:latest /usr/bin/composer /usr/bin/composer

        # Copy PHP config
        COPY mclogs.ini /usr/local/etc/php/conf.d/mclogs.ini

        WORKDIR /web/mclogs
    volumes:
      - ../:/web/mclogs
  mongo:
    image: mongo
    volumes:
      - mongo:/data/db
volumes:
  mongo: